version: '3.8'

services:

  postgres:
    image: postgres:14
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_DB=user_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user

  redis:
    image: redis:7.0.12
    ports:
      - "6379:6379"
