spring:
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: true
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5433}/${DATABASE_NAME:user_db}
    username: ${DATABASE_USERNAME:user}
    password: ${DATABASE_PASSWORD:user}
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: user_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS user_schema
      connection-timeout: 10000

app:
  jwt:
    secret: someSecretKey
    tokenExpiration: 3m
    refreshTokenExpiration: 30m